### ISSUE TITLE
Handle `vite-plugin-static-copy`

### ISSUE THREAD

**Issue by Vinorcola** [lhapaipai/vite-plugin-symfony#43]
### Description

Hi,

I'm not sure if it is possible, but it would be nice to handle file copied by the `vite-plugin-static-copy`. It comes in replacement for the `copyFiles` function in `webpack-encore`.

Currently, it is not possible because the copied files are not included in the `entrypoints.json`, and thus are not usable with the symfony's `asset` twig function.

### Previously in `webpack-encore` expisode...

```js
// webpack.config.js
Encore.copyFiles([
    {
        from: "node_modules/jquery/dist",
        pattern: /jquery\.min\.js$/,
        to: "jquery.[hash:8].js",
    },
])
```

```twig
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/jquery.min.js') }}"></script>
{% endblock %}
```

### With vite

```js
// vite.config.js
export default defineConfig({
    plugins: [
        checker({
            typescript: true,
        }),
        react(),
        symfonyPlugin(),
        viteStaticCopy({
            targets: [
                {
                    src: "node_modules/jquery/dist/jquery.min.js",
                    dest: "static",
                    rename: "jquery.js",
                },
            ],
        }),
    ],
    build: {
        rollupOptions: {
            input: {
                // Others inputs here.
            },
        },
    },
})
```

```twig
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('build/static/jquery.js') }}"></script>
{% endblock %}
```

**Comment by andyexeter** [comment]
Hi @Vinorcola - this can be done without a plugin by using [explicit URL imports](https://vitejs.dev/guide/assets#explicit-url-imports):

```js
// main.js
import '../node_modules/jquery/dist/jquery.min.js?url';
```

```twig
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('node_modules/jquery/dist/jquery.min.js') }}"></script>
{% endblock %}
```

**Comment by lhapaipai** [comment]
Hi @Vinorcola and @andyexeter,
indeed there is an issue and Explicit URL Imports unfortunately does not solve it because it gives us the path to the file without copying it to a folder accessible to the web.

the `vite-plugin-static-copy` plugin does not inform rollup of what it is doing which is why the manifest file does not contain the desired entry. but in our case we know the build directory so a little bit of code can allow us to correct the issue.

fixed in v6.4.6

you will need to set the vite-bundle `throw_on_missing_asset` option to false

```yaml
# config/packages/pentatrion_vite.yaml
pentatrion_vite:
    throw_on_missing_asset: false
```

more details on the doc Reference [throw_on_missing_asset](https://symfony-vite.pentatrion.com/reference/vite-bundle.html#throw-on-missing-asset)

**Comment by andyexeter** [comment]
I'm glad to see the issue is fixed, however I just wanted to clarify that Explicit URL Imports _do_ make the file accessible to the web.

I set up a basic example here: https://stackblitz.com/edit/vitejs-vite-fdohwh?file=main.js

You can see that the jquery.min.js file is copied to dist/assets as jquery.min-CK9_Gmfi.js

**Comment by lhapaipai** [comment]
hi @andyexeter,
I agree with you after a build step the file is copied to dist/assets.

but I encounter several problems with your way that I have not been able to resolve:
- the file is not available before a build step (now that our build directory is no longer emptied by default when we start the vite dev server it's less a problem but it's still not very intuitive)
- the path './node_modules/jquery/dist/jquery.min.js?url' is not portable by default between package managers
  - with yarn 3 for example we doesn't have a `node_modules` directory by default
  - with pnpm after build step my manifest.json is

```json
{
  "assets/main.js": {
    "file": "assets/main-DF9J71zs.js",
    "name": "main",
    "src": "assets/main.js",
    "isEntry": true,
    "assets": [
      "assets/jquery.min-CK9_Gmfi.js"
    ]
  },
  "node_modules/.pnpm/jquery@3.7.1/node_modules/jquery/dist/jquery.min.js": {
    "file": "assets/jquery.min-CK9_Gmfi.js",
    "src": "node_modules/.pnpm/jquery@3.7.1/node_modules/jquery/dist/jquery.min.js"
  }
}
```
this add extra work to get "assets/jquery.min-CK9_Gmfi.js" from "node_modules/.pnpm/jquery@3.7.1/node_modules/jquery/dist/jquery.min.js" wich doesn't look like to "node_modules/jquery/dist/jquery.min.js"

at the time the solution provided seemed easier to implement
